name: Build and Test 
 
on: 
  push: 
    branches: [ main ]  # Run on pushes to the main branch 
 
jobs: 
  build-and-test: 
    runs-on: ubuntu-latest  # Run on Ubuntu virtual machine 
 
    steps: 
      - uses: actions/checkout@v4  # Checkout code from the repository 
      - name: Build (demo)
        run: echo "Build step ran"
      - name: Test (demo)
        run: echo "Tests passed"
